---
name: "ICA2 - Group C"
on:
  push: 
    branches:
      - 'develop'

jobs:
  build:
    name: Build distribution
    runs-on: linuxvmforica2

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install -r requirement.txt
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/